import type { BlendFactor, ParticleState } from "./types";

export const BLEND_MAP: Record<BlendFactor, number> = {
  ZERO: 0,
  ONE: 1,
  SRC_COLOR: 768,
  ONE_MINUS_SRC_COLOR: 769,
  SRC_ALPHA: 770,
  ONE_MINUS_SRC_ALPHA: 771,
  DST_ALPHA: 772,
  ONE_MINUS_DST_ALPHA: 773,
  DST_COLOR: 774,
  ONE_MINUS_DST_COLOR: 775,
};

export const DEFAULT_STATE: ParticleState = {
  backgroundColor: "#000000",
  duration: 0.1,
  infinite: true,
  maxParticles: 200,
  life: 0.2,
  lifeVar: 0,
  angle: 180,
  angleVar: 180,
  sourceW: 14,
  sourceH: 14,
  positionType: "FREE",
  emitterType: "0",
  gravityX: 0.25,
  gravityY: 0.86,
  speed: 0,
  speedVar: 190.79,
  radialAccel: 0,
  radialAccelVar: 0,
  tangentialAccel: 0,
  tangentialAccelVar: 0,
  maxRadius: 80,
  maxRadiusVar: 0,
  minRadius: 0,
  minRadiusVar: 0,
  rotatePerSecond: 180,
  rotatePerSecondVar: 0,
  startColor: "#cfcf55",
  startColorVar: "#e5ffbe",
  useTextureColor: true,
  endColor: "#afaa09",
  endColorVar: "#6fe7e7",
  startAlpha: 1,
  endAlpha: 0,
  texturePath: "static/template/atom.png",
  textureName: "atom.png",
  startSize: 3.37,
  startSizeVar: 50,
  endSize: 30.32,
  endSizeVar: 0,
  rotationStart: -47.37,
  rotationStartVar: 0,
  rotationEnd: -47.37,
  rotationEndVar: -142.11,
  blendSrc: "SRC_ALPHA",
  blendDst: "ONE",
  saveName: "particle",
};

export const PRESETS = {
  fireworks: {
    backgroundColor: "#000000",
    duration: 0.1,
    infinite: true,
    maxParticles: 200,
    life: 1.6,
    lifeVar: 0.2,
    angle: 90,
    angleVar: 29,
    sourceW: 0.1,
    sourceH: 0.1,
    positionType: "FREE",
    emitterType: "0",
    gravityX: 0.25,
    gravityY: -835,
    speed: 519,
    speedVar: 134,
    radialAccel: 0,
    radialAccelVar: 0,
    tangentialAccel: 0,
    tangentialAccelVar: 0,
    maxRadius: 80,
    maxRadiusVar: 0,
    minRadius: 0,
    minRadiusVar: 0,
    rotatePerSecond: 180,
    rotatePerSecondVar: 0,
    startColor: "#ffffff",
    startColorVar: "#000000",
    useTextureColor: true,
    endColor: "#ffffff",
    endColorVar: "#000000",
    startAlpha: 1,
    endAlpha: 0,
    texturePath: "atom.png",
    textureName: "atom.png",
    startSize: 15,
    startSizeVar: 0,
    endSize: 0,
    endSizeVar: 0,
    rotationStart: 0,
    rotationStartVar: 0,
    rotationEnd: 0,
    rotationEndVar: 0,
    blendSrc: "SRC_ALPHA",
    blendDst: "ONE",
  },
} satisfies Record<string, Omit<ParticleState, "saveName">>;

export type PresetName = keyof typeof PRESETS;

export function createInitialState(): ParticleState {
  return { ...DEFAULT_STATE, ...PRESETS.fireworks };
}
